@ContactsWebAPI_HostAddress = https://localhost:7028

GET {{ContactsWebAPI_HostAddress}}/weatherforecast/
Accept: application/json

###

GET {{ContactsWebAPI_HostAddress}}/api/contactsapi/Contacts

###
